### PR TITLE
Fix series preview table height on the course page

### LINKED ISSUE #3962: Series navigation should always bring selected series to top of viewport
In [this course](https://dodona.ugent.be/en/courses/773/) with multiple series, this is the view I get after clicking the "exam (group 2)" series in the series nagivation in the right margin:

image

Two issues:

1. The series is not on top of the viewport, even though there's enough content below it to make this happen.
2. Another series is highlighted in the series navigation.

This no longer happens after series skeletons have been replaced with the full rendering of the series. A height difference between skeletons and full renderings of series might cause this issue (@chvp witnesses having observed this issue upon page loading).

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request is a third attempt to fix #3962. See #4167 and  #4169 for previous attempts.

This pull request contains two parts:
- A replacement of the old table preview. The new table preview has the correct height in all browser and also contains the activity name as requested by @niknetniko .
- A speed up of the progress bar load, to offset reduced speed by the new table.

## Analysis
To analyze the impact of these changes, I looked at two large courses. For fair comparison I disabled memcached and the sql query cache. 

### http://dodona.ugent.be/nl/courses/800/
102 series | 640 exercises | 488 users | 491.449 submissions

| Pr    | Total request time | Time in views | Time in Activerecord | Filesize |
|-------|--------------|---------------|----------------------|----------|
| Old   | 755ms        | 620.0ms       | 125.4ms              | 833KB    |
| #4167 | 2049ms       | 1780.3ms      | 228.3ms              |          |
| #4169 | 6947ms       | 2827.0ms      | 4101.8ms             |          |
| New   | 1049ms       | 838.6ms       | 200.3ms              | 990KB    |

### http://dodona.ugent.be/nl/courses/359/
22 series | 90 exercises | 623 users | 355.789 submissions

| Pr    | Total request time | Time in views | Time in Activerecord | Filesize |
|-------|--------------|---------------|----------------------|----------|
| Old   | 2006ms       | 394.3ms       | 1603.1ms             | 296 KB   |
| #4167 | 1931ms       | 463.9ms       | 1456.2ms             |          |
| #4169 | 1879ms       | 684.6ms       | 1182.8ms             |          |
| New   | 970ms        | 352.4ms       | 607.9ms              | 326.3KB  |

### Notes
The speed up is much less noticeable for the first course. This is due to the first two series of that course being exams in which few students participated. 
In the second course the speedup is much greater then the slowdown, caused by loading the activity names.

In order to limit the increase in file size, I tried to keep the amount of html for each row to a minimum.

## Visual
Old
image

New
image

Closes #3962 .

PS: this pr also containes some changes to the generated database file.
This is probably caused by me having a backup of production on my machine.
I would keep these changes in as they reflect the state of the production database.

### CODE REVIEW

**Comment by jorg-vr** [comment]
@bmesuere 
1. Should be fixed now. Forgot to correctly set the `SKELETON_TABLE_SELECTOR` after testing
2. I switched back to the old height. The height difference was to match the height of the elements in the actual table

File: app/models/submission.rb [hunk 1]
```diff
@@ -60,7 +60,7 @@ class Submission < ApplicationRecord
   scope :of_judge, ->(judge) { where(exercise_id: Exercise.where(judge_id: judge.id)) }
   scope :from_students, ->(course) { where(user: course.enrolled_members) }
 
-  scope :judged, -> { where.not(status: %i[running queued]) }
+  scope :judged, -> { where(status: ['unknown', 'correct', 'wrong', 'time limit exceeded', 'runtime error', 'compilation error', 'memory limit exceeded', 'internal error', 'output limit exceeded']) }
```
Comment (chvp) [inline app/models/submission.rb:63]: Maybe add a comment here on why this can't be a `where.not`?

**Review by chvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]

**Comment by pdawyndt** [comment]
Feels great to have this issue resolved!
