### PR TITLE
Fix refreshing of course members page after actions

### LINKED ISSUE #4968: Delete student from course
When deleting a student from a course as a course admin, the table is not refreshed (student is removed though).

### PR DESCRIPTION
**Pull request by jorg-vr**
Closes #4968

### CODE REVIEW

File: app/views/courses/_reload_users.js.erb [hunk 1]
```diff
@@ -3,5 +3,7 @@
   new dodona.Toast("<%= toast %>");
 <% end %>
 <% count = @course.pending_members.count %>
-document.getElementById("pending-count").innerText = "<%= count if count.nonzero? %>";
+if(document.getElementById("pending-count")) {
```
Comment (chvp) [inline app/views/courses/_reload_users.js.erb:6]:
```suggestion
if (document.getElementById("pending-count")) {
```

**Review by chvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]
I think the problem here was that getElementById returned null which caused innerText to fail, which in turn stopped the execution of the rest of the code? I expect we'll have more issues like this due to the jquery migration.

Too bad you can't use optional chaining in the left hand side of an assignment and that there is no way to set innerText using a function.
