### PR TITLE
better ordering of exercises in series

### LINKED ISSUE #1080: wrong order of exercises in series
When a new series is created with more than 16 exercises, the order of the exercises in that series will differ from the order the exercises were added.

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1080) by @dmouriss on Tue May 21 2019 at 16:43._

### PR DESCRIPTION
**Pull request by winniederidder**
Fixes #1080

### CODE REVIEW

File: app/models/series_membership.rb [hunk 1]
```diff
@@ -16,7 +16,7 @@ class SeriesMembership < ApplicationRecord
 
   delegate :course, to: :series
 
-  default_scope { order(order: :asc) }
+  default_scope { order(order: :asc, id: :desc) }
```
Comment (charvp) [inline app/models/series_membership.rb]:
```suggestion
  default_scope { order(order: :asc, id: :asc) }
```
