### PR TITLE
Fix series indicator on course page

### LINKED ISSUE #5560: Exercise series indicator is broken
Current series should be in bold and have a vertical line in front.

https://github.com/dodona-edu/dodona/assets/56451049/90fa6be0-21c2-459f-80c7-e318c8dc5228

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request fixes the correct series indicator being shown as active on the course page.

Probably a change in the series card structure caused this to fail.

Closes #5560.

### CODE REVIEW

File: app/assets/javascripts/scrollspy.ts [hunk 1]
```diff
@@ -75,13 +75,12 @@ export class ScrollSpy {
...
-            * @type {HTMLElement}
-            */
-            const section = this.sections[i];
-            // get the parent of the parent of the anchor
-            const startAt = section.parentElement.parentElement.offsetTop;
-            const endAt = startAt + section.parentElement.parentElement.offsetHeight;
+            const section: HTMLElement = this.sections[i];
+            // this is a series card specific modification
+            // it gets the great grand parent of the anchor tag, which is the series card
+            const seriesCard = section.parentElement.parentElement.parentElement;
```
Comment (bmesuere) [inline app/assets/javascripts/scrollspy.ts:81]: While this fixes the issue, it is still prone to breaking due to changes in the structure. I would traverse the tree and check for a specific tag/class/id instead.

**Review by bmesuere — CHANGES_REQUESTED** [review]

**Review by bmesuere — APPROVED** [review]
Ah, I didn't even know `closest` existed :)

**Review by niknetniko — APPROVED** [review]
