### PR TITLE
Only use judged submission to determine exercise and series status

### LINKED ISSUE #1322: exercises that are being evaluated, are displayed as incorrect
The exercise below contains no previous submissions. While the exercise was being evaluated, the status at the course overview was "Incorrect" (see image below) instead of "Evaluating..."

image

### PR DESCRIPTION
**Pull request by charvp**
Also fixes the `users_tried` and `attempted_exercises` to only take judged submissions into account.

- [x] Tests were added
- No relevant documentation.

Closes #1322.

### CODE REVIEW

File: test/models/transient/exercise_summary.rb [hunk 1]
```diff
@@ -282,6 +282,28 @@ def summary
     end
   end
 
+  class NotJudgedYet < ExerciseSummaryTest
```
Comment (bmesuere) [inline test/models/transient/exercise_summary.rb]: NotYetJudged?

**Comment by charvp** [comment]
Cache invalidation happens on every submission update, so will still work and the frequency won't change.
