### PR TITLE
Fix error messages when uploading incorrect user labels

### LINKED ISSUE #4129: Error message during CSV labels upload is not shown
The error is sent back using JS, but something seems to go wrong during its execution (or maybe it's not executed at all?).

### PR DESCRIPTION
**Pull request by jorg-vr**
While working on the code, I also removed jquery. (Progress on #3590 )

Closes #4129.

### CODE REVIEW

File: app/assets/javascripts/course.ts [hunk 1]
```diff
@@ -78,7 +80,20 @@ function initCourseMembers(): void {
             fetch(`/courses/${modal.dataset.course_id}/members/upload_labels_csv`, {
                 method: "POST",
                 body: formData,
-            }).then(loadUsers);
+            }).then(async response => {
+                if (!response.ok) {
```
Comment (niknetniko) [inline app/assets/javascripts/course.ts:84]: I would only show this specific error if we know there was no file. For example, if I try uploading something else, like an image, we get a 500 server error (maybe something for another PR), but the message is still "please upload a file".

**Review by niknetniko — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/course.ts (hunk 1 above)
Comment (jorg-vr) [reply app/assets/javascripts/course.ts:85]: Old alerts are now removed. And I added a specific check for malformed csv which should cover a lot of cases

**Review by niknetniko — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]
