### PR TITLE
Fix ctrl click for notifications

### LINKED ISSUE #5247: Ctrl + click'ing a notification opens the link in both current and new tab
I had a new notification today, and wanted to open it in a new tab. On many websites this can be done by pressing ctrl + clicking the link, click it with the third mouse-button (often the mouse-wheel), or right-click and select "Open link in new tab".

The last 2 options work as expected, but ctrl + click 'ing the link opens the link in the current open tab and in a new tab.

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request fixes #5247 if the actual link part of the notification is clicked. (quite common)

It is not solved in al cases as that would increase complexity to much and be prone to errors due to different browser behavior. See https://github.com/dodona-edu/dodona/pull/5276/commits/9f592aa7a834ad4362ef05e3f8f14991326abbfb and https://robertcooper.me/post/table-row-links

Closes #5247

### CODE REVIEW

File: app/assets/javascripts/notification.ts [hunk 1]
```diff
@@ -42,6 +42,9 @@ export class Notification {
         // We only want to install the click handler for the full element on the small notification view.
         if (installClickHandler) {
             this.element.addEventListener("click", event => {
+                // Use default browse behavior if the user clicked on the link itself.
```
Comment (chvp) [inline app/assets/javascripts/notification.ts:45]:
```suggestion
                // Use default browser behavior if the user clicked on the link itself.
```

**Review by chvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]
