### PR TITLE
Don't fetch first and last submission for timeseries if none are present

### LINKED ISSUE #3367: Timeseries fails on empty data
Timeseries data prep sometimes throws an error:

```
A NoMethodError occurred in statistics#timeseries:

  undefined method `created_at' for nil:NilClass
  app/models/submission.rb:432:in `timeseries_matrix'

-------------------------------
Request:
-------------------------------

  * URL        : https://dodona.ugent.be/nl/stats/timeseries?series_id=12607

```

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request fixes a bug when timeseries tried to fetch the first and last submission when none are present.

Now a message is shown explaining that no data is availlable:
image

Closes #3367 .

### CODE REVIEW

File: app/models/submission.rb [hunk 1]
```diff
@@ -429,8 +429,8 @@ def self.timeseries_matrix(options = {})
     submissions = submissions.judged
     submissions = submissions.from_students(options[:series].course)
 
-    first_sub = submissions.least_recent.first.created_at
-    last_sub = submissions.most_recent.first.created_at
+    first_sub = submissions.present? ? submissions.least_recent.first.created_at : nil
+    last_sub = submissions.present? ? submissions.most_recent.first.created_at : nil
```
Comment (chvp) [inline app/models/submission.rb:433]: I feel like `.any?` instead of `.present?` makes more sense semantically?

**Review by chvp — CHANGES_REQUESTED** [review]
With small bugfixes like this, I always try to add a simple test covering the wrong behaviour. Just to make sure we don't regress later.

**Review by chvp — APPROVED** [review]

**Review by bmesuere — APPROVED** [review]

**Review by niknetniko — APPROVED** [review]
