### PR TITLE
Stop previous papyros execution on new debug run

### LINKED ISSUE #5361: Should stop previous papyros execution before starting a new one
see https://dodona.be/nl/submissions/16963306/

The debug case doesn't stop as it is waiting for input.
Clicking debug on another case without explicitly stopping the previous causes a crash

### PR DESCRIPTION
**Pull request by jorg-vr**
This pull request fixes  #5361 

I will refactor this in papyros so we only need `await papyros.codeRunner.stop();` on the dodona side. But decided to already push this now to fix the bug.

Closes #5361

### CODE REVIEW

File: app/assets/javascripts/tutor.ts [hunk 1]
```diff
@@ -49,6 +49,16 @@ export function initTutor(submissionCode: string): void {
     async function loadTutor(exerciseId: string, studentCode: string, statements: string, stdin: string, inlineFiles: Record<string, string>, hrefFiles: Record<string, string>): Promise<void> {
         const papyros = await initPapyros(ProgrammingLanguage.Python);
 
+        if (papyros.codeRunner.getState() != RunState.Ready && papyros.codeRunner.getState() != RunState.Loading) {
```
Comment (bmesuere) [inline app/assets/javascripts/tutor.ts:52]:
```suggestion
        if (papyros.codeRunner.getState() !== RunState.Ready && papyros.codeRunner.getState() !== RunState.Loading) {
```

File: app/assets/javascripts/tutor.ts [hunk 2]
```diff
@@ -49,6 +49,16 @@ export function initTutor(submissionCode: string): void {
...
+            // stop the code runner if it is running
+            await papyros.codeRunner.stop();
+
+            // wait to make sure the code runner is stopped
+            while (papyros.codeRunner.getState() == RunState.Stopping) {
```
Comment (bmesuere) [inline app/assets/javascripts/tutor.ts:57]:
```suggestion
            while (papyros.codeRunner.getState() === RunState.Stopping) {
```

**Review by bmesuere — APPROVED** [review]
